name: Build check

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Build check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.7

    - name: Build solution (NET Framework)
      run: msbuild STB-DiffChecker.sln /p:Configuration=Debug

# Uncomment these lines if you want to run tests
#    - name: Run tests (NET Core)
#      run: dotnet test --no-build -c debug

#    - name: Run tests (NET Framework)
#      run: vstest.console.exe YourTestProject.dll
