name: Build check

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Build check
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build solution (NET Framework)
      run: msbuild STB-DiffChecker.sln /p:Configuration=Debug

# Uncomment these lines if you want to run tests
#    - name: Run tests (NET Core)
#      run: dotnet test --no-build -c debug

#    - name: Run tests (NET Framework)
#      run: vstest.console.exe YourTestProject.dll
